// CarHomesVue/src/components/AppFooter.vue
<template>
  <footer class="footer bg-dark text-white py-4">
    <div class="container">
      <p class="text-center mb-0">© 2024 CarHomes. Todos los derechos reservados.</p>
      <p class="text-center mb-0">
        <a href="https://twitter.com/vuejs" target="_blank" rel="noopener" class="text-white">Síguenos en Twitter</a> |
        <a href="https://github.com/vuejs" target="_blank" rel="noopener" class="text-white">GitHub</a> |
        <a href="https://www.vuejs.org" target="_blank" rel="noopener" class="text-white">Web Oficial</a>
      </p>
    </div>
  </footer>
</template>

<style scoped>
.footer {
  width: 100%;
  position: relative; 
}
</style>

// CarHomesAngular/src/app/components/app-footer/app-footer.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-footer',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './app-footer.component.html',
  styleUrls: ['./app-footer.component.css']
})
export class AppFooterComponent {

}

<footer class="footer bg-dark text-white py-4">
  <div class="container">
    <p class="text-center mb-0">© 2024 CarHomes. Todos los derechos reservados.</p>
    <p class="text-center mb-0">
      <a href="https://twitter.com/vuejs" target="_blank" rel="noopener" class="text-white">Síguenos en Twitter</a> |
      <a href="https://github.com/vuejs" target="_blank" rel="noopener" class="text-white">GitHub</a> |
      <a href="https://www.vuejs.org" target="_blank" rel="noopener" class="text-white">Web Oficial</a>
    </p>
  </div>
</footer>
